### ISSUE TITLE
Uncorrectly PATH expected.

### ISSUE THREAD

**Issue by hrivera2014** [kjay23/powerline-bash#2]
When ctrl-shift-t or new terminal is open the PATH becomes  /home/user directory and not the currently in use directory.

**Comment by kjay23** [comment]
What Terminal software did you use? I'm not really sure if you are using other than Konsole since it actually opened in the same directory where I am currently working on it.

**Comment by hrivera2014** [comment]
Hi, thanks. I'm using gnome-terminal in Fedora 34. I test installing konsole and effectively works well as you has stated.
